name: CI

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run RSpec tests
        run: |
          mkdir -p results
          bundle exec rspec

      - name: Upload RSpec JUnit results to Trunk.io
        if: "!cancelled()"
        uses: trunk-io/analytics-uploader@v1
        with:
          junit-paths: "results/rspec.xml"
          org-slug: byteforge
          token: ${{ secrets.TRUNK_API_TOKEN }}
        continue-on-error: true

